#!/usr/bin/env python

import os
import sys
from lxml import etree
from xml.etree import ElementTree

try:
    xmcda_dir = os.path.dirname(os.readlink(os.path.abspath(__file__)))
except:
    xmcda_dir = os.path.dirname(os.path.abspath(__file__))

XMCDA_200 = xmcda_dir + '/XMCDA-2.0.0.xsd'
XMCDA_210 = xmcda_dir + '/XMCDA-2.1.0.xsd'
XMCDA_220 = xmcda_dir + '/XMCDA-2.2.0.xsd'
XMCDA_221 = xmcda_dir + '/XMCDA-2.2.1.xsd'
XMCDA_SCHEMAS = [XMCDA_200, XMCDA_210, XMCDA_220, XMCDA_221]

def usage():
    print("%s files" % os.path.basename(sys.argv[0]))

def validate(xml, schema):
    doc = etree.parse(schema)
    schema = etree.XMLSchema(doc)
    return schema.validate(xml)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        usage()
        sys.exit(1)

    ret = 0
    for xmlfile in sys.argv[1:]:
        try:
            tree = etree.parse(open(xmlfile, 'r'))
        except:
            print("%s is NOT a valid XML file" % xmlfile)
            ret = 1
            continue

        valid = False
        for schema in XMCDA_SCHEMAS:
            if validate(tree, schema) is True:
                valid = True
                break

        if valid is True:
            print("%s is a valid XMCDA file" % xmlfile)
        else:
            print("%s is NOT a valid XMCDA file" % xmlfile)
            ret = 1

    sys.exit(ret)
